### ISSUE TITLE
Question regarding calculation of theta/rho parameter for PSMC

### ISSUE THREAD

**Issue by squisquater** [cdomsar/DivgLupaster#1]
Can you elaborate on how you calculated the -r parameter for the PSMC analysis? 

I understand that parameter to be Ө(genetic diversity)/p(recombination rate).

In your paper you stated that Өπ was used as theta (θ) (see Supporting Information Code File 03) and that you estimated genome wide rho from a recombination map for dogs (Auton et al., 2013). I see from Table 4 that Өπ was probably ~8.55 ± 4.15*10^−4 for the Algerian wolf and I do understand how to calculate that parameter (either using SFS or mlRho for example). 

I then see that you ended up setting -r to 6.3291 for the Algerian wolf.

Based on that info I then inferred that your rho parameter must have been ~1.3*10^-4. I'm just not sure how you got that from the Auton et al. recombination map which I think has an average recombination rate of ~1.2-1.3cM/Mb. Does it have something do with needing to scale the recombination rate since p=4Nr ? If so, I'm not clear on how that is done exactly with the information you had available here. 

I know that you can also infer rho from mlRho but I am curious to know how you ended up getting there and hope to use that as a comparison to my estimates from mlRho.

**Comment by carlos-sarabia** [comment]
Hi Sophie! Thanks for the question. I appreciate this and I had to go back to my notes to see why I had written this. 

The answer is in the PSMC README file:
"If you want to plot the result with your own scripts, you can increase \theta_0 to \theta_0/(1-FNR)."

The default -r in PSMC is 5, assuming that the coverage is enough to consistently plot the PSMC (which would need to be >15X, according to Nadachowska-Brzyska et al., 2016 doi: 10.1111/mec.13540). However, in downsampled genomes from 24X to 15X I observed a deviation from the original curve (Fig. S1), so I applied a FNR correction to all genomes. In genomes around 24X (Kenya, Ethiopia) I used -r5, but corrections needed to be applied to the Algerian AGW (which lost 21% heterozygosity, FNR=0.21),  East Morocco (FNR=11), West Morocco (FNR=0.18) and Senegal (FNR=0.35). They are in Fig. S1C (Fig. 3 has a mistake and says Algeria[0.11] but is in fact Algeria[0.21]). 

If theta_0 is 5 for genomes with >15X depth of coverage (24X in the case of the Ethiopian and Kenyan genomes), theta_0/(1-FNR) is theta_0/(1-0.21) in the case of Algeria. Assuming that theta_0 and rho are the same across the species, rPSMC = theta_0/(rho*(1-FNR)); so -r is 5/(1-0.21)=6.3291 in the case of Algeria, 5/(1-0.11)=5.6179 in East Morocco, 5/(1-0.18)=6.0975 in West Morocco, and 5/(1-0.35)=7.6923 in the case of Senegal. 

I hope this helps!
